services:
  db:
    image: postgres:15
    container_name: vpn_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" # Private
    networks:
      - vpn_net

  redis:
    image: redis:7-alpine
    container_name: vpn_redis
    restart: always
    networks:
      - vpn_net
    ports:
      - "127.0.0.1:6379:6379"

  minio:
    image: minio/minio
    container_name: vpn_minio
    env_file: .env
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:9000:9000"  # S3 API (Private to HAProxy)
      - "127.0.0.1:9090:9090"  # Web UI (Private to HAProxy)
    restart: always
    networks:
      - vpn_net

  django:
    build: .
    container_name: vpn_django
    restart: always
    env_file: .env
    command: ["sh", "/app/app.sh"]
    # volumes:
    #   - .:/app
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - vpn_net

volumes:
  postgres_data:
  minio_data:

networks:
  vpn_net:
    driver: bridge # Change to bridge for internal container communication
