# Generated by Django 4.2.17 on 2026-07-30 07:06

import apps.vpn.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VpnPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "volume_gb",
                    models.PositiveIntegerField(help_text="Total traffic volume in GB"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Total validity in days"),
                ),
                ("max_concurrent_users", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "price"],
            },
        ),
        migrations.CreateModel(
            name="VpnPricingConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price_per_gb", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_per_extra_days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Charged only for days beyond free_days",
                        max_digits=10,
                    ),
                ),
                (
                    "price_per_extra_user",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price for each concurrent user beyond the first",
                        max_digits=10,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "free_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="First N days of a custom plan's duration are free; only days beyond this are billed",
                    ),
                ),
                ("min_gb", models.PositiveIntegerField(default=10)),
                ("max_gb", models.PositiveIntegerField(default=1000)),
                ("gb_step", models.PositiveIntegerField(default=10)),
                ("min_days", models.PositiveIntegerField(default=7)),
                ("max_days", models.PositiveIntegerField(default=365)),
                ("min_users", models.PositiveIntegerField(default=1)),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "VPN Pricing Config",
                "verbose_name_plural": "VPN Pricing Config",
            },
        ),
        migrations.CreateModel(
            name="UserVpnSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional user-given name, e.g. 'For my brother'",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("fixed", "Fixed Plan"), ("custom", "Custom Plan")],
                        max_length=10,
                    ),
                ),
                ("volume_gb", models.PositiveIntegerField()),
                ("duration_days", models.PositiveIntegerField()),
                ("max_concurrent_users", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Admin Approval"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("used_traffic_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("xui_inbound_ids", models.JSONField(blank=True, default=list)),
                (
                    "xui_client_uuid",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "xui_client_subid",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "xui_client_email",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("subscription_link", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="vpn.vpnplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("purchase", "Initial Purchase"),
                            ("renewal", "Renewal / Top-up"),
                        ],
                        default="purchase",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount this specific payment covers (snapshot at submission time)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("extra_days", models.PositiveIntegerField(default=0)),
                ("extra_gb", models.PositiveIntegerField(default=0)),
                (
                    "receipt_image",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=apps.vpn.models.payment_proof_upload_to,
                    ),
                ),
                (
                    "receipt_text",
                    models.TextField(
                        blank=True,
                        help_text="Transaction reference / free text note from the user",
                    ),
                ),
                ("ai_checked", models.BooleanField(default=False)),
                (
                    "ai_verdict",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'likely_genuine', 'suspicious'",
                        max_length=20,
                    ),
                ),
                ("ai_notes", models.TextField(blank=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        help_text="null = pending, True = approved, False = rejected",
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payment_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_proofs",
                        to="vpn.uservpnsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
