# Generated by Django 4.2.17 on 2026-07-30 22:16

import apps.vpn.models
import config.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentproof",
            name="receipt_image",
            field=models.FileField(
                blank=True,
                max_length=500,
                storage=config.utils.storages.PrivateMediaStorage(),
                upload_to=apps.vpn.models.payment_proof_upload_to,
            ),
        ),
    ]
