# Generated by Django 4.2.17 on 2026-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vpn", "0002_alter_paymentproof_receipt_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservpnsubscription",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
