# Generated by Django 4.2.30 on 2026-09-23 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_uservpnsubscription_hidden_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='XuiInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_id', models.PositiveIntegerField(help_text="The inbound's id on the 3x-ui panel", unique=True)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('is_enabled_on_panel', models.BooleanField(default=True)),
                ('exists_on_panel', models.BooleanField(default=True, help_text='False when the latest sync did not return this inbound')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '3x-ui inbound',
                'ordering': ['panel_id'],
            },
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='admin_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the receipt was posted to the Telegram admins. Empty = not announced yet.', null=True),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(condition=models.Q(('admin_notified_at__isnull', True)), fields=['created_at'], name='vpn_proof_unannounced_idx'),
        ),
        migrations.AddField(
            model_name='inboundgroup',
            name='inbounds',
            field=models.ManyToManyField(blank=True, related_name='groups', to='vpn.xuiinbound'),
        ),
        migrations.AddField(
            model_name='vpnplan',
            name='inbound_group',
            field=models.ForeignKey(blank=True, help_text='Inbounds a purchase of this plan is created on. Empty = the default group.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='vpn.inboundgroup'),
        ),
        migrations.AddConstraint(
            model_name='inboundgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='vpn_single_default_inbound_group'),
        ),
    ]
