# Generated by Django 4.2.30 on 2026-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_backfill_proof_admin_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('bot', 'Telegram bot')], default='app', max_length=10),
        ),
    ]
