# Generated by Django 4.2.17 on 2026-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_backfill_paymentproof_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservpnsubscription',
            name='expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservpnsubscription',
            name='low_volume_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservpnsubscription',
            name='total_traffic_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
