# Generated by Django 4.2.17 on 2026-10-08 06:03

from django.db import migrations, models
from django.db.models import F


def backfill(apps, schema_editor):
    UserVpnSubscription = apps.get_model("vpn", "UserVpnSubscription")
    PaymentProof = apps.get_model("vpn", "PaymentProof")
    # Best available record of what was bought. A service renewed under the
    # old carry-over rule may already have drifted; nothing better exists.
    UserVpnSubscription.objects.filter(purchased_volume_gb__isnull=True).update(
        purchased_volume_gb=F("volume_gb")
    )
    # Everything approved so far was applied on approval - nothing is queued.
    PaymentProof.objects.filter(is_approved=True, applied_at__isnull=True).update(
        applied_at=F("reviewed_at")
    )
    PaymentProof.objects.filter(is_approved=True, applied_at__isnull=True).update(
        applied_at=F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_subscription_reminders_and_exact_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservpnsubscription',
            name='purchased_volume_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
