# Generated by Django 4.2.17 on 2026-06-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coachservicerequest",
            name="client",
        ),
        migrations.RemoveField(
            model_name="coachservicerequest",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="coachservicerequest",
            name="service",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="revenuesplit",
            name="beneficiary",
        ),
        migrations.RemoveField(
            model_name="revenuesplit",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="CoachService",
        ),
        migrations.DeleteModel(
            name="CoachServiceRequest",
        ),
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
        migrations.DeleteModel(
            name="RevenueSplit",
        ),
    ]
