# Generated by Django 4.2.17 on 2026-07-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_coach",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_gym_owner",
        ),
    ]
