# Generated by Django 4.2.17 on 2026-08-09 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_identifiers(apps, schema_editor):
    User = apps.get_model("account", "User")

    for user in User.objects.filter(identifier__isnull=True).iterator():
        user.identifier = uuid.uuid4().hex
        user.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_otp_required",
                    models.BooleanField(
                        default=False,
                        help_text="When on, a new email signup must confirm a code before the account is created, and existing unverified accounts are warned in their profile.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Auth Settings",
                "verbose_name_plural": "Auth Settings",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="identifier",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_identifiers,
                             reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),

        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
            ),
        ),

        migrations.RunSQL(
            sql="""
                UPDATE account_user
                SET phone_number = NULL
                WHERE phone_number = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
            ),
        ),

        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", models.CharField(db_index=True, max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")], max_length=10
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register_phone", "Register with phone"),
                            ("register_email", "Register with email"),
                            ("login_phone", "Sign in with phone"),
                            ("add_email", "Attach an email"),
                            ("add_phone", "Attach a phone number"),
                            ("reset_password", "Reset password"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target", "purpose", "-created_at"],
                        name="account_otp_target_21e455_idx",
                    )
                ],
            },
        ),
    ]
