# Generated by Django 4.2.17 on 2026-08-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0002_authsettings_user_identifier_user_is_email_verified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identifier",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
