# Generated by Django 4.2.17 on 2026-09-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="identifier",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
