# Generated by Django 4.2.30 on 2026-09-23 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_alter_telegramprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('login', 'Sign in to the app'), ('link', 'Connect to an app account')], max_length=10)),
                ('start_token_hash', models.CharField(max_length=64, unique=True)),
                ('poll_secret_hash', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=4)),
                ('opened_by_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the bot'), ('confirmed', 'Confirmed in the bot'), ('used', 'Session handed out'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('moved_subscriptions', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_auth_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
