# Generated by Django 4.2.30 on 2026-09-24 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_clear_legacy_bot_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_username', models.CharField(blank=True, help_text="The bot's username without '@', e.g. my_vpn_bot. Leave empty to use the one the bot container detects when it starts. When set, it is used even if the running bot is a different one.", max_length=32)),
                ('detected_bot_username', models.CharField(blank=True, editable=False, help_text='Recorded by the bot container from its own token each time it starts.', max_length=32)),
                ('detected_at', models.DateTimeField(blank=True, editable=False, help_text='When the bot container last recorded its username.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot Settings',
                'verbose_name_plural': 'Telegram Bot Settings',
            },
        ),
    ]
